Inventory on string metrics
hawkular/hawkular-agent pull request #303
Opened 2017-03-13 15:47 UTC by jotak

2017-03-13 15:50 UTC, jotak commented
... need to set org.hawkular.metrics.string-size to -1 in metrics config db...

2017-03-13 17:23 UTC, jmazzitelli commented
Putting a hold on any changes/PR merges to the agent until we decide what to do about this major refactoring effort going on right now (see PR #302 ). I've got over 200 files changed (many are wholesale moving of large chunks of files) and any thing going in now it going to potentially involve major conflicts. To avoid any git pain, going to wait until that major refactor is complete. Should be soon.

2017-03-13 17:28 UTC, jotak commented
Ok, anyway, this change must also be coordinated with the MIQ side and other parts (hServices...) so it's not ready to be merged so fast

2017-03-15 19:10 UTC, jmazzitelli commented
The agent refactor is complete and merged into master. As expected, this PR is affected. Major conflict resolution required.

2017-03-16 14:29 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/service/AgentCoreEngine.java
> -                        registerFeed(tenantIds);
@jmazzitelli : I removed registerFeed as it doesn't have to be explicitly setup now. Except if you think that a feed should have an existence even if it has nothing associated with (no metric type, no resource type, no root resource)... in which case I should rollback this part.

2017-03-16 14:32 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/storage/AsyncInventoryStorage.java
>                  // FIXME: make sure "," cannot be used in ids, or choose another character
(note for self: need a fix here)

2017-04-11 09:14 UTC, jotak commented
@jmazzitelli can you have a look at the last commit? ( https://github.com/hawkular/hawkular-agent/pull/303/commits/6000ce76bb66376445513b63f8fc43b166fd5adc )

Following our discussion yesterday, I made some changes to avoid unnecessary updates. Had to refactor some code.

2017-04-11 09:30 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +     * Creates a discovery event.
Will update javadoc

2017-04-11 12:58 UTC, jmazzitelli requested changes

2017-04-11 12:58 UTC, jmazzitelli commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +     * @return the map of removed resources during this discovery
The javadoc for this and the one above (getRemovedRootResources, getAddedOrModifiedRootResources) seems wrong. These return the root resources of all the resources that were removed (or added/modified). These root resources weren't necessarily added or removed (though they could have been, too), but they are the root resources of the resources that were added or removed. Right?

2017-04-11 12:58 UTC, jmazzitelli commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +    public List<Resource<L>> getRemoved() {
Here you should add javadoc to these two (getAddedOrModified, getRemoved) explaining that these are the actual resources that were added/modified and removed (which is different than the getXYZRootResources methods).

2017-04-11 13:19 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +     * @return the map of removed resources during this discovery
Yes, that's correct. I'm doing a javadoc cleaning pass

2017-04-11 13:35 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +     * Creates a discovery event.
done

2017-04-11 13:36 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +     * @return the map of removed resources during this discovery
done

2017-04-11 13:40 UTC, jmazzitelli commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +            addedOrModifiedRootResources.put(root.getID().getIDString(), root);
Lines 83 and 84 tell me that "addedOrModifiedRootResources" will contain the roots of all resources that were added or modified. Is this what you intended? So if a resource changes one of its resource config properties (i.e. it is modified) then its root resource will go into this addedOrModifiedRootResources map (in that case the root isn't really modified - its list of descendants didn't change with a new resource added or old resource removed - it is just that one of its descendants (child, grandchild, or lower) got modified - in this case, do you want the root resource to be considered "modified")?

2017-04-11 13:55 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/api/InventoryEvent.java
> +            addedOrModifiedRootResources.put(root.getID().getIDString(), root);
Yes, this is what is intended. The reason is that the whole root resource subtree is going to be persisted. So we need to separate root resources that have 1 modification (at least) wherever in their subtree = `addedOrModifiedRootResources` map ; and root resources that need to be entirely deleted = `removedRootResources` map.

2017-04-14 06:40 UTC, jotak commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/storage/AsyncInventoryStorage.java
> +                log.infof("Updating root resource: %s", r.getID().getIDString());
@jmazzitelli are you fine with those 3 log.info (also line 444 and 435) that happen every time inventory storage is updated? That can be interesting for tracing http calls, but if you prefer I can put to debug level (or remove).

2017-04-14 11:55 UTC, jmazzitelli commented on hawkular-agent-core/src/main/java/org/hawkular/agent/monitor/storage/AsyncInventoryStorage.java
> +                log.infof("Updating root resource: %s", r.getID().getIDString());
you can move them to debug level

2017-04-21 14:13 UTC, jmazzitelli commented
@metlos took this PR and built upon it and that is now PR #320 which supercedes this PR. This PR will be closed.

2017-04-24 21:51 UTC, jmazzitelli commented
PR #325 is the one we are going to use - close this one

2017-04-24 21:51 UTC, closed without merging