[WIP] Adding the automation for pushihg the docker images by Travis
hawkular/hawkular-agent pull request #317
Opened 2017-04-12 15:49 UTC by Jiri-Kremser

It's done only if there is a new release.

It's basically done, but I still need to test it.

2017-04-13 20:31 UTC, jmazzitelli requested changes

2017-04-13 20:31 UTC, jmazzitelli commented on .travis.yml
> +  fi
No good. Looking at travis output I see syntax errors in the docker script at this if stmt. Here's the output:

```
$ if [[ "$TRAVIS_TAG" != ""]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then ./.travis.push.docker.images.sh fi
/home/travis/.travis/job_stages: eval: line 53: conditional binary operator expected
/home/travis/.travis/job_stages: eval: line 53: syntax error near `"${TRAVIS_BRANCH}"'
/home/travis/.travis/job_stages: eval: line 53: `if [[ "$TRAVIS_TAG" != ""]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then ./.travis.push.docker.images.sh fi '
```

2017-04-18 13:11 UTC, Jiri-Kremser commented on .travis.yml
> +  fi
it looks better now

2017-04-19 14:38 UTC, jmazzitelli approved these changes

2017-04-19 14:43 UTC, merged